### ISSUE TITLE
Settings Explanation

### ISSUE THREAD

**Issue by phreakazoid21** [LukasPatzke/ambientHUE#12]
Hello,
I was hoping someone can help me understand something. 
I don't really understand the two On/Off entries in the Settings for lights and groups.  

What is "On/Off" and what is "Managed On/Off"?  How are they different? 

Thank you!

**Comment by LukasPatzke** [comment]
Hi,

The setting "On/Off" enables ambientHUE for the light. If this setting is off, nothing happens. If it is on, ambientHUE takes control over the properties of the light that you configure below.

If you enable the setting "Manage On/Off", ambientHUE will turn on the light as soon as the current curve value exceeds the "On/Off Threshold" value.

If you enable the setting "Manage Brightness", ambientHUE will adjust the brightness value for the light according to the current curve value.

If you enable the setting "Manage Colour Temperature", ambientHUE will adjust the colour temperature value for the light according to the current curve value.

These three settings can be used independent from each other.
Of course, the availability of the settings depends on the capabilities of the physical light.

I hope that this was helpful.
